import React, { useState, useMemo } from 'react';
import { 
  Save, 
  RotateCcw, 
  CheckCircle2, 
  AlertCircle, 
  ArrowRight, 
  Layout, 
  List, 
  Code, 
  Zap, 
  ChevronRight, 
  X, 
  Copy,
  TrendingUp,
  DollarSign,
  Package
} from 'lucide-react';
import { GenericItem, DocumentContext, BusinessRule } from '../types';
import confetti from 'canvas-confetti';
import { db, collection, addDoc, serverTimestamp, handleFirestoreError, OperationType } from '../firebase';

interface GeneratedFormProps {
  items: GenericItem[];
  context: DocumentContext | null;
  rule: BusinessRule | null;
  onReset: () => void;
}

const GeneratedForm: React.FC<GeneratedFormProps> = ({ items, context, rule, onReset }) => {
  const [formData, setFormData] = useState<GenericItem[]>(items);
  const [viewMode, setViewMode] = useState<'form' | 'catalog'>('form');
  const [showSource, setShowSource] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const handleInputChange = (index: number, newValue: string) => {
    const updated = [...formData];
    updated[index] = { ...updated[index], value: newValue };
    setFormData(updated);
  };

  const totalValue = useMemo(() => {
    return formData.reduce((acc, item) => {
      const val = String(item.value || '').replace(/[^0-9.]/g, '');
      const num = parseFloat(val);
      return acc + (isNaN(num) ? 0 : num);
    }, 0);
  }, [formData]);

  const appliedBenefit = useMemo(() => {
    if (!rule) return null;
    const threshold = rule.threshold || 0;
    const value = rule.value || 0;
    if (rule.type === 'discount' && totalValue >= threshold) {
      return {
        message: `System Alert: ${value}% Discount Applied`,
        saving: (totalValue * value) / 100,
        type: 'success'
      };
    }
    if (rule.type === 'flag' && totalValue >= threshold) {
      return {
        message: `System Alert: High Value Threshold Reached`,
        type: 'warning'
      };
    }
    return null;
  }, [rule, totalValue]);

  const getCollectionName = (type: string) => {
    const t = type.toLowerCase();
    if (t.includes('student') || t.includes('college')) return 'student_registrations';
    if (t.includes('patient') || t.includes('hospital')) return 'patient_intakes';
    if (t.includes('restaurant') || t.includes('menu')) return 'restaurant_menus';
    return 'general_submissions';
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      const collectionName = getCollectionName(context?.detectedType || '');
      const dataToSave: any = {
        createdAt: serverTimestamp(),
        data: formData.reduce((acc, item) => ({ ...acc, [item.id || item.name]: item.value }), {})
      };

      // Map specific fields for schema validation
      formData.forEach(item => {
        const label = item.name.toLowerCase();
        if (label.includes('name')) {
          if (collectionName === 'student_registrations') dataToSave.name = item.value;
          if (collectionName === 'patient_intakes') dataToSave.patientName = item.value;
          if (collectionName === 'restaurant_menus') dataToSave.itemName = item.value;
        }
        if (label.includes('email')) dataToSave.email = item.value;
        if (label.includes('id')) dataToSave.studentId = item.value;
        if (label.includes('course')) dataToSave.course = item.value;
        if (label.includes('price')) dataToSave.price = parseFloat(String(item.value).replace(/[^0-9.]/g, '')) || 0;
        if (label.includes('category')) dataToSave.category = item.value;
      });

      await addDoc(collection(db, collectionName), dataToSave);
      
      setIsSubmitting(false);
      setIsSuccess(true);
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#ffffff', '#71717a', '#27272a']
      });
    } catch (error) {
      console.error(error);
      setIsSubmitting(false);
      // Let handleFirestoreError handle the logging and throwing
      try {
        handleFirestoreError(error, OperationType.WRITE, getCollectionName(context?.detectedType || ''));
      } catch (e) {
        alert("Submission failed: " + (e instanceof Error ? e.message : "Unknown error"));
      }
    }
  };

  const sourceCode = `
import React, { useState } from 'react';

// Auto-generated by BizFlow Architect
export const GeneratedApp = () => {
  const [data, setData] = useState(${JSON.stringify(formData, null, 2)});
  
  return (
    <div className="p-8 bg-zinc-950 text-white">
      <h1 className="text-2xl font-bold mb-6">${context?.detectedType || 'Process Interface'}</h1>
      <form className="space-y-4">
        {data.map((item, i) => (
          <div key={i} className="flex flex-col gap-2">
            <label className="text-sm font-medium text-zinc-400">{item.name}</label>
            <input 
              className="bg-zinc-900 border border-zinc-800 rounded-lg p-2"
              value={item.value} 
            />
          </div>
        ))}
      </form>
    </div>
  );
};
  `.trim();

  if (isSuccess) {
    return (
      <div className="max-w-xl mx-auto text-center space-y-8 py-20 animate-fade-in">
        <div className="inline-flex items-center justify-center w-20 h-20 bg-emerald-500/10 rounded-full text-emerald-500 mb-4">
          <CheckCircle2 size={40} />
        </div>
        <div className="space-y-2">
          <h2 className="text-3xl font-semibold text-white">Submission Successful</h2>
          <p className="text-zinc-500">The process data has been synchronized with the enterprise backend.</p>
        </div>
        <div className="flex justify-center gap-4">
          <button onClick={() => setIsSuccess(false)} className="btn-secondary">View Record</button>
          <button onClick={onReset} className="btn-primary">New Synthesis</button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-fade-in">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-1">
          <h2 className="text-2xl font-semibold text-white">{context?.detectedType || 'Process Interface'}</h2>
          <p className="text-sm text-zinc-500">Synthesized from source document • {formData.length} Active Fields</p>
        </div>

        <div className="flex items-center gap-2 p-1 bg-zinc-900 rounded-lg border border-zinc-800">
          <button 
            onClick={() => setViewMode('form')}
            className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-xs font-medium transition-all ${viewMode === 'form' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-500 hover:text-zinc-300'}`}
          >
            <Layout size={14} />
            <span>Form View</span>
          </button>
          <button 
            onClick={() => setViewMode('catalog')}
            className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-xs font-medium transition-all ${viewMode === 'catalog' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-500 hover:text-zinc-300'}`}
          >
            <List size={14} />
            <span>Catalog View</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          {viewMode === 'form' ? (
            <div className="card-minimal p-8">
              <form onSubmit={handleSubmit} className="space-y-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
                  {formData.map((item, idx) => (
                    <div key={idx} className="space-y-2">
                      <label className="text-xs font-medium text-zinc-500 uppercase tracking-widest ml-1">{item.name}</label>
                      <input 
                        type="text"
                        value={item.value}
                        onChange={(e) => handleInputChange(idx, e.target.value)}
                        className="w-full input-minimal text-sm"
                      />
                    </div>
                  ))}
                </div>

                <div className="pt-8 border-t border-zinc-900 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4">
                  <button type="button" onClick={onReset} className="text-zinc-500 hover:text-white transition-colors text-sm font-medium flex items-center justify-center gap-2 py-2">
                    <RotateCcw size={16} />
                    <span>Reset</span>
                  </button>
                  <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
                    <button type="button" onClick={() => setShowSource(true)} className="btn-secondary text-sm flex items-center justify-center gap-2 py-2.5 px-4">
                      <Code size={16} />
                      <span>View Source</span>
                    </button>
                    <button type="submit" disabled={isSubmitting} className="btn-primary text-sm flex items-center justify-center gap-2 py-2.5 px-6">
                      {isSubmitting ? (
                        <div className="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin"></div>
                      ) : (
                        <>
                          <Save size={16} />
                          <span>Commit Changes</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>
              </form>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {formData.map((item, idx) => (
                <div key={idx} className="card-minimal p-6 flex items-start gap-4 hover:border-zinc-700 transition-colors">
                  <div className="p-3 bg-zinc-900 rounded-xl text-zinc-400">
                    <Package size={20} />
                  </div>
                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">{item.name}</p>
                    <p className="text-sm font-medium text-white">{item.value}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="space-y-6">
          <div className="card-minimal p-6 space-y-6">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold uppercase tracking-widest text-zinc-500">Financial Summary</h3>
              <DollarSign size={16} className="text-zinc-600" />
            </div>
            
            <div className="space-y-4">
              <div className="flex justify-between items-end">
                <span className="text-sm text-zinc-400">Aggregated Value</span>
                <span className="text-2xl font-semibold text-white">${totalValue.toLocaleString()}</span>
              </div>
              
              {appliedBenefit && (
                <div className={`p-4 rounded-xl border ${appliedBenefit.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-amber-500/10 border-amber-500/20 text-amber-400'}`}>
                  <div className="flex items-start gap-3">
                    {appliedBenefit.type === 'success' ? <CheckCircle2 size={16} className="shrink-0" /> : <AlertCircle size={16} className="shrink-0" />}
                    <div className="space-y-1">
                      <p className="text-xs font-bold uppercase tracking-wider">{appliedBenefit.message}</p>
                      {appliedBenefit.saving && (
                        <p className="text-[10px] font-medium opacity-80 italic">Estimated Savings: ${appliedBenefit.saving.toLocaleString()}</p>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {rule && (
                <div className="pt-4 border-t border-zinc-900 space-y-3">
                  <div className="flex items-center justify-between text-[10px] font-bold text-zinc-600 uppercase tracking-widest">
                    <span>Active Logic</span>
                    <Zap size={10} />
                  </div>
                  <div className="p-3 bg-zinc-950 border border-zinc-900 rounded-lg">
                    <p className="text-[11px] text-zinc-400 leading-relaxed italic">"{rule.originalText}"</p>
                  </div>
                  <div className="space-y-1">
                    <div className="flex justify-between text-[10px] font-medium text-zinc-500">
                      <span>Threshold Progress</span>
                      <span>{Math.min(100, Math.round((totalValue / (rule.threshold || 1)) * 100))}%</span>
                    </div>
                    <div className="h-1 w-full bg-zinc-900 rounded-full overflow-hidden">
                      <div 
                        className={`h-full transition-all duration-1000 ${totalValue >= (rule.threshold || 0) ? 'bg-emerald-500' : 'bg-zinc-700'}`}
                        style={{ width: `${Math.min(100, (totalValue / (rule.threshold || 1)) * 100)}%` }}
                      ></div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>

          <div className="card-minimal p-6 bg-zinc-900/20 border-dashed border-zinc-800 space-y-4">
            <div className="flex items-center gap-3 text-zinc-500">
              <TrendingUp size={18} />
              <h3 className="text-xs font-bold uppercase tracking-widest">Process Insights</h3>
            </div>
            <p className="text-[11px] text-zinc-500 leading-relaxed">
              Our neural engine has identified potential optimizations for this workflow. Automated reconciliation is recommended for high-value items.
            </p>
          </div>
        </div>
      </div>

      {showSource && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
          <div className="w-full max-w-3xl card-minimal bg-zinc-950 overflow-hidden flex flex-col max-h-[80vh]">
            <div className="p-4 border-b border-zinc-900 flex items-center justify-between bg-zinc-900/30">
              <div className="flex items-center gap-3">
                <Code size={18} className="text-zinc-500" />
                <h3 className="text-sm font-semibold text-white">Synthesized React Component</h3>
              </div>
              <button onClick={() => setShowSource(false)} className="p-1 hover:bg-zinc-800 rounded-md transition-colors text-zinc-500">
                <X size={20} />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-6 bg-black">
              <pre className="text-xs font-mono text-zinc-400 leading-relaxed">
                <code>{sourceCode}</code>
              </pre>
            </div>
            <div className="p-4 border-t border-zinc-900 bg-zinc-900/30 flex justify-end gap-3">
              <button 
                onClick={() => {
                  navigator.clipboard.writeText(sourceCode);
                  alert('Source code copied to clipboard');
                }}
                className="btn-secondary text-xs flex items-center gap-2"
              >
                <Copy size={14} />
                <span>Copy Code</span>
              </button>
              <button onClick={() => setShowSource(false)} className="btn-primary text-xs">Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default GeneratedForm;
